import type {
  AssessmentQuestionResponse,
  AssessmentResponse,
  ChildResponse,
  ReportResponse,
  UserResponse,
  WeeklyPlanResponse,
} from "@/types/api";

export const fixtureUser: UserResponse = {
  id: "user-1",
  email: "parent@example.com",
  display_name: "ولي الأمر",
  created_at: "2026-01-01T00:00:00Z",
};

export const fixtureChild: ChildResponse = {
  id: "child-1",
  name: "سارة",
  date_of_birth: "2022-01-01",
  gender: "female",
  home_language: "ar",
  has_previous_diagnosis: false,
  previous_diagnosis_details: null,
  has_hearing_problems: false,
  uses_hearing_aid: false,
  notes: null,
  age_years: 4,
  is_assessment_age_eligible: true,
  created_at: "2026-01-01T00:00:00Z",
  updated_at: "2026-01-01T00:00:00Z",
};

export const fixtureQuestions: AssessmentQuestionResponse[] = [
  {
    id: "Q001",
    age: 4,
    domain: "اللغة الاستقبالية",
    question: "هل يستجيب الطفل عند مناداة اسمه؟",
    linked_milestone_id: "RL001",
  },
  {
    id: "Q002",
    age: 4,
    domain: "اللغة الاستقبالية",
    question: "هل ينفذ تعليمات بسيطة؟",
    linked_milestone_id: "RL002",
  },
];

export const fixtureAssessmentInProgress: AssessmentResponse = {
  id: "assessment-1",
  child_id: "child-1",
  age_at_assessment: 4,
  status: "in_progress",
  started_at: "2026-01-01T00:00:00Z",
  completed_at: null,
  answered_count: 0,
  total_questions: 2,
  overall_severity: null,
  overall_referral: null,
  confidence_score: null,
  priority_domains: [],
  strengths: [],
  support_needs: [],
  domain_results: [],
};

export const fixtureAssessmentCompleted: AssessmentResponse = {
  ...fixtureAssessmentInProgress,
  status: "completed",
  completed_at: "2026-01-01T00:10:00Z",
  answered_count: 2,
  overall_severity: "طبيعي",
  overall_referral: "لا",
  confidence_score: 1,
  priority_domains: ["اللغة الاستقبالية"],
  strengths: ["الاستجابة للاسم"],
  support_needs: [],
  domain_results: [
    {
      domain: "اللغة الاستقبالية",
      score_percent: 100,
      severity: "طبيعي",
      referral: "لا",
      decision_rule_id: "R001",
      recommendation: "استمر في الأنشطة اليومية المناسبة للعمر.",
      follow_up: "إعادة التقييم بعد 3 أشهر",
      suggested_activity_ids: ["A001", "A002"],
    },
  ],
};

export const fixtureReport: ReportResponse = {
  id: "report-1",
  report_number: "REP-0001",
  language: "ar",
  child_id: "child-1",
  child_name: "سارة",
  child_age_years: 4,
  assessment_id: "assessment-1",
  generated_at: "2026-01-01T00:15:00Z",
  overall_severity: "طبيعي",
  overall_referral: "لا",
  referral_recommended: false,
  confidence_score: 1,
  domain_summaries: [
    { domain: "اللغة الاستقبالية", score_percent: 100, severity: "طبيعي", recommendation: "استمر." },
  ],
  strengths: ["الاستجابة للاسم"],
  support_needs: [],
  summary_text: "أظهر التقييم أن الطفل يحقق المهارات اللغوية المتوقعة لعمره.",
  weekly_goal: "التركيز على اللغة الاستقبالية.",
  recommended_activity_ids: ["A001", "A002"],
  next_reassessment: "3 أشهر",
  disclaimer: "هذا التطبيق أداة داعمة لولي الأمر ولا يغني عن التقييم أو العلاج من قبل أخصائي تخاطب مؤهل.",
};

export const fixtureWeeklyPlan: WeeklyPlanResponse = {
  id: "plan-1",
  child_id: "child-1",
  assessment_id: "assessment-1",
  is_active: true,
  generated_at: "2026-01-01T00:20:00Z",
  total_activities: 2,
  completed_count: 0,
  adherence_percent: 0,
  activities: [
    {
      id: "slot-1",
      day: "الأحد",
      slot_order: 1,
      completed: false,
      completed_at: null,
      activity: {
        source_file: "KB02.xlsx",
        source_sheet: "Activities",
        id: "A001",
        name: "تنفيذ التعليمات البسيطة",
        age: 4,
        domain: "اللغة الاستقبالية",
        target_skill: "فهم التعليمات",
        goal: "تحسين فهم التعليمات",
        description: "يطلب من الطفل تنفيذ أوامر من خطوة واحدة.",
        tools: "ألعاب منزلية",
        duration: "10 دقائق",
        frequency: "يوميًا",
        difficulty: "سهل",
        parent_instructions: "استخدم جملًا قصيرة.",
        expected_outcome: "تحسن الاستجابة للتعليمات",
        reference: "ASHA",
      },
    },
    {
      id: "slot-2",
      day: "الأحد",
      slot_order: 2,
      completed: false,
      completed_at: null,
      activity: {
        source_file: "KB02.xlsx",
        source_sheet: "Activities",
        id: "A002",
        name: "لعبة الإشارة",
        age: 4,
        domain: "اللغة الاستقبالية",
        target_skill: "فهم الإشارة",
        goal: "تحسين فهم الإشارة",
        description: "اطلب من الطفل الإشارة إلى أجزاء جسمه.",
        tools: "لا يوجد",
        duration: "10 دقائق",
        frequency: "يوميًا",
        difficulty: "سهل",
        parent_instructions: "كرر الطلب بصبر.",
        expected_outcome: "تحسن الفهم",
        reference: "ASHA",
      },
    },
  ],
};
