"""create reports table

Revision ID: 557306bf79e4
Revises: 7b7b7ed8a434
Create Date: 2026-07-21 20:13:46.603021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.database import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = '557306bf79e4'
down_revision: Union[str, Sequence[str], None] = '7b7b7ed8a434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('report_number', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('summary_text', sa.String(length=2000), nullable=False),
    sa.Column('weekly_goal', sa.String(length=500), nullable=False),
    sa.Column('next_reassessment', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_number')
    )
    op.create_index(op.f('ix_reports_assessment_id'), 'reports', ['assessment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_assessment_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
