"""create children table

Revision ID: 75dea2fb2a05
Revises: 84d407bdcd2d
Create Date: 2026-07-21 19:43:15.021803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.database import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = '75dea2fb2a05'
down_revision: Union[str, Sequence[str], None] = '84d407bdcd2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('children',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('home_language', sa.String(length=50), nullable=False),
    sa.Column('has_previous_diagnosis', sa.Boolean(), nullable=False),
    sa.Column('previous_diagnosis_details', sa.Text(), nullable=True),
    sa.Column('has_hearing_problems', sa.Boolean(), nullable=False),
    sa.Column('uses_hearing_aid', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_user_id'), 'children', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_children_user_id'), table_name='children')
    op.drop_table('children')
    # ### end Alembic commands ###
