"""create assessment tables

Revision ID: 7b7b7ed8a434
Revises: 75dea2fb2a05
Create Date: 2026-07-21 19:54:20.087376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.database import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = '7b7b7ed8a434'
down_revision: Union[str, Sequence[str], None] = '75dea2fb2a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('age_at_assessment', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', UTCDateTime(), nullable=True),
    sa.Column('overall_severity', sa.String(length=30), nullable=True),
    sa.Column('overall_referral', sa.String(length=30), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_child_id'), 'assessments', ['child_id'], unique=False)
    op.create_table('assessment_answers',
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(length=20), nullable=False),
    sa.Column('response', sa.String(length=20), nullable=False),
    sa.Column('score_weight', sa.Float(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'question_id')
    )
    op.create_index(op.f('ix_assessment_answers_assessment_id'), 'assessment_answers', ['assessment_id'], unique=False)
    op.create_table('assessment_domain_results',
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('score_percent', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('referral', sa.String(length=30), nullable=False),
    sa.Column('decision_rule_id', sa.String(length=20), nullable=False),
    sa.Column('recommendation', sa.String(length=1000), nullable=False),
    sa.Column('follow_up', sa.String(length=255), nullable=False),
    sa.Column('suggested_activity_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'domain')
    )
    op.create_index(op.f('ix_assessment_domain_results_assessment_id'), 'assessment_domain_results', ['assessment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_domain_results_assessment_id'), table_name='assessment_domain_results')
    op.drop_table('assessment_domain_results')
    op.drop_index(op.f('ix_assessment_answers_assessment_id'), table_name='assessment_answers')
    op.drop_table('assessment_answers')
    op.drop_index(op.f('ix_assessments_child_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
