"""create weekly plan tables

Revision ID: b207c1b32664
Revises: 557306bf79e4
Create Date: 2026-07-21 20:20:37.982136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.database import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = 'b207c1b32664'
down_revision: Union[str, Sequence[str], None] = '557306bf79e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_plans',
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_plans_child_id'), 'weekly_plans', ['child_id'], unique=False)
    op.create_table('weekly_plan_activities',
    sa.Column('weekly_plan_id', sa.String(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('slot_order', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.String(length=20), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', UTCDateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['weekly_plan_id'], ['weekly_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weekly_plan_id', 'day', 'slot_order')
    )
    op.create_index(op.f('ix_weekly_plan_activities_weekly_plan_id'), 'weekly_plan_activities', ['weekly_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_plan_activities_weekly_plan_id'), table_name='weekly_plan_activities')
    op.drop_table('weekly_plan_activities')
    op.drop_index(op.f('ix_weekly_plans_child_id'), table_name='weekly_plans')
    op.drop_table('weekly_plans')
    # ### end Alembic commands ###
