"""create followups table

Revision ID: ca8a1d34b622
Revises: b207c1b32664
Create Date: 2026-07-21 20:31:35.656199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.database import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = 'ca8a1d34b622'
down_revision: Union[str, Sequence[str], None] = 'b207c1b32664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followups',
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('previous_assessment_id', sa.String(), nullable=False),
    sa.Column('current_assessment_id', sa.String(), nullable=False),
    sa.Column('previous_score_percent', sa.Float(), nullable=False),
    sa.Column('current_score_percent', sa.Float(), nullable=False),
    sa.Column('improvement_percent', sa.Float(), nullable=False),
    sa.Column('improved_domains', sa.JSON(), nullable=False),
    sa.Column('support_needed_domains', sa.JSON(), nullable=False),
    sa.Column('comment', sa.String(length=2000), nullable=False),
    sa.Column('next_goal', sa.String(length=500), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('current_assessment_id')
    )
    op.create_index(op.f('ix_followups_child_id'), 'followups', ['child_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_followups_child_id'), table_name='followups')
    op.drop_table('followups')
    # ### end Alembic commands ###
